eureka:
  client:
    register-with-eureka: false
server:
  port: 8222

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product
          uri: http://localhost:8090
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        - id: cart
          uri: http://localhost:8070
          predicates:
            - Path=/api/carts/**
          filters:
            - AuthenticationFilter

        - id: auth
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/auth/**
