spring:
  application:
    name: cart

  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/product-service


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true  # Ensures that Eureka uses IP address instead of hostname
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # Eureka server URL
    fetch-registry: true  # Allow fetching the registry
    register-with-eureka: true  # Register the service with Eureka

server:
  port: 8070  # The server port for this application